### ISSUE TITLE
Deepvariant fails with message "Check failed: alt_to_alleles.size() == allele_map.size() Non-unique alternative alleles!"

### ISSUE THREAD

**Issue by RolandFaure** [google/deepvariant#991]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.9/docs/FAQ.md**:
Yes

**Describe the issue:**
I'm running DeepVariant to call variant in a metagenomic context. It really worked well on several example, but one fails with the error message
Check failed: alt_to_alleles.size() == allele_map.size() Non-unique alternative alleles!
It is indeed very possible that multiple alternatives alleles are present in one locus. Is it possible to circumvent the problem? Or a least know which contig is bugging and remove it? Thanks :)

**Setup**
  - Operating system: Fedora 8.10
  - DeepVariant version: 1.8.0
  - Installation method (Docker, built from source, etc.): Singularity
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?): ONT data. Used in a metagenomic context, to call variants against an assembly obtained by assembling the reads with Flye.

**Steps to reproduce:**
  - Command: singularity run -B $PWD/$out_dir/tmp:/tmp -B /usr/lib/locale/:/usr/lib/locale/ -B /pasteur/helix/projects/seqbio/rfaure/metacaller/human_gut/out_deepvariant/tmp:/local/scratch/tmp -B /pasteur/helix/projects/seqbio/rfaure/metacaller/human_gut:/mnt/data --env TMPDIR=/tmp docker://google/deepvariant:"1.8.0" /opt/deepvariant/bin/run_deepvariant --model_type=ONT_R104 --vcf_stats_report=true --ref=/mnt/data/$(basename $reference) --reads=/mnt/data/mapped.bam --output_vcf=/mnt/data/out_deepvariant/output.vcf.gz --num_shards=$threads
  - Error trace:
```
*** Check failure stack trace: ***
    @     0x7fa41ea9c76d  absl::lts_20230802::log_internal::LogMessageFatal::~LogMessageFatal()
    @     0x7fa41e457d8e  learning::genomics::deepvariant::multi_sample::AddReadDepths()
    @     0x7fa41e556bc5  learning::genomics::deepvariant::multi_sample::VariantCaller::CallVariant()
    @     0x7fa41e55624c  learning::genomics::deepvariant::multi_sample::VariantCaller::AlleleCountsGenerator<>()
    @     0x7fa41e556730  learning::genomics::deepvariant::multi_sample::VariantCaller::CallsFromAlleleCounts()
    @     0x7fa41e54b21e  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
    @     0x7fa41e4d47ca  pybind11::cpp_function::dispatcher()
    @     0x55e2bc800282  (unknown)
Fatal Python error: Aborted

Current thread 0x00007fa42021b000 (most recent call first):
  File "/tmp/Bazel.runfiles_nazv65a0/runfiles/com_google_deepvariant/deepvariant/very_sensitive_caller.py", line 58 in get_candidates
  File "/tmp/Bazel.runfiles_nazv65a0/runfiles/com_google_deepvariant/deepvariant/variant_caller.py", line 450 in calls_and_gvcfs
  File "/tmp/Bazel.runfiles_nazv65a0/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 2530 in candidates_in_region
  File "/tmp/Bazel.runfiles_nazv65a0/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 2020 in process
  File "/tmp/Bazel.runfiles_nazv65a0/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 3027 in make_examples_runner
  File "/tmp/Bazel.runfiles_nazv65a0/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 224 in main
  File "/tmp/Bazel.runfiles_nazv65a0/runfiles/absl_py/absl/app.py", line 258 in _run_main
  File "/tmp/Bazel.runfiles_nazv65a0/runfiles/absl_py/absl/app.py", line 312 in run
  File "/tmp/Bazel.runfiles_nazv65a0/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 234 in <module>
```

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Yes, it works. Other similar instances ran with the same command line ran too.

**Comment by lucasbrambrink** [comment]
Hi,

We think that this may have been fixed in our latest release. You can try running version 1.9.0 and see if that fixes the issue. If that does not work, you can set `--output_debug_info` to find the problematic region.

**Comment by RolandFaure** [comment]
Thanks for your quick answer!
Updating to 1.9.0 did not solve the issue, which remains identical :(
I'm now running it with `--output_debug_info`, I'll keep you informed

**Comment by pichuan** [comment]
Hi @RolandFaure ,

`output_debug_info` is a flag for make_examples. So, if you're using the one-step `run_deepvariant` directly (instead of splitting the steps on your own), please add:

```
  --make_examples_extra_args="output_debug_info=true"
```
